language: csharp
mono:
  - latest
solution: LibraryManagement.sln
install:
  - nuget restore LibraryManagement.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /p:VbcToolExe=vbnc.exe LibraryManagement.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Tests/bin/Release/LibraryManagement.Tests.dll --exclude:TravisExclude
after_success:
- coveralls